### ISSUE TITLE
Annotations for local dataset

### ISSUE THREAD

**Issue by meetdave06** [visipedia/annotation_tools#10]
Hi,
I am trying to create annotations for custom dataset. From what I understand, I will have to create an empty JSON file in COCO format with the URL of images in dataset.

Is there any script to create json file in COCO format for custom dataset? Thanks.

**Comment by meetdave06** [comment]
Update:

I managed to make annotation file for the custom dataset. After loading the annotation file in DB, I am not able to get the image loaded in the browser. It doesn't throw any error as well.

The images are hosted on my local server using SimpleHTTPServer. I double checked the url as well. No problem there.

My sample annotation :- 

'{
	"info": {
		"description": "Dataset",
		"url": "https://gitlab.com/QDemo",
		"version": "0.1.0",
		"year": 2019,
		"contributor": "meet dave",
		"date_created": "2019-01-25 13:08:02.769183"
	},
	"licenses": [{
		"url": "http://creativecommons.org/licenses/by-nc-sa/2.0/",
		"id": 1,
		"name": "Attribution-NonCommercial-ShareAlike License"
	}],
	"images": [{
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000003.jpg",
		"file_name": "0000003.jpg",
		"id": 3,
		"coco_url": "http://localhost:8007/images/0000003.jpg",
		"height": 1080
	}, {
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000002.jpg",
		"file_name": "0000002.jpg",
		"id": 2,
		"coco_url": "http://localhost:8007/images/0000002.jpg",
		"height": 1080
	}, {
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000004.jpg",
		"file_name": "0000004.jpg",
		"id": 4,
		"coco_url": "http://localhost:8007/images/0000004.jpg",
		"height": 1080
	}, {
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000001.jpg",
		"file_name": "0000001.jpg",
		"id": 1,
		"coco_url": "http://localhost:8007/images/0000001.jpg",
		"height": 1080
	}, {
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000006.jpg",
		"file_name": "0000006.jpg",
		"id": 6,
		"coco_url": "http://localhost:8007/images/0000006.jpg",
		"height": 1080
	}, {
		"width": 1920,
		"date_captured": "2019-01-25 13:08:05.142750",
		"license": 1,
		"flickr_url": "http://localhost:8007/images/0000005.jpg",
		"file_name": "0000005.jpg",
		"id": 5,
		"coco_url": "http://localhost:8007/images/0000005.jpg",
		"height": 1080
	}],
	"annotations": [{
		"image_id": 3,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 3,
		"keypoints": []
	}, {
		"image_id": 2,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 2,
		"keypoints": []
	}, {
		"image_id": 4,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 4,
		"keypoints": []
	}, {
		"image_id": 1,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 1,
		"keypoints": []
	}, {
		"image_id": 6,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 6,
		"keypoints": []
	}, {
		"image_id": 5,
		"segmentation": [],
		"num_keypoints": 0,
		"bbox": [],
		"area": null,
		"category_id": 1,
		"iscrowd": 0,
		"id": 5,
		"keypoints": []
	}],
	"categories": [{
		"supercategory": "person",
		"skeleton": [
			[16, 14],
			[14, 12],
			[17, 15],
			[15, 13],
			[12, 13],
			[6, 12],
			[7, 13],
			[6, 7],
			[6, 8],
			[7, 9],
			[8, 10],
			[9, 11],
			[2, 3],
			[1, 2],
			[1, 3],
			[2, 4],
			[3, 5],
			[4, 6],
			[5, 7]
		],
		"id": 1,
		"keypoints": ["nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"],
		"name": "person"
	}]
}'

Kindly let me know if I am making a mistake somewhere.

**Comment by meetdave06** [comment]
Hi,
I have figured it out. The problem was that I was giving an empty list for key points, bbox and segmentation. Initialized with zeros and works fine.

**Comment by ankhzaya** [comment]
Hello, I have the same problem. Even though I initialized with zeros for key points, bbox and segmentation, still I can't show any images in the browser? Do you have any suggestion for me? Thank you

**Comment by meetdave06** [comment]
@ankhzaya  Just make sure that none of the keys are empty and have some values in it. It will overwrite them once you start tagging.
