### ISSUE TITLE
Just get Visipedia Annotation Toolkit at the webset

### ISSUE THREAD

**Issue by jingshaoli** [visipedia/annotation_tools#12]
This is what I get.
![image](https://user-images.githubusercontent.com/44631784/57573118-60207b00-745e-11e9-8cb7-de0b38be59ff.png)
This is what I do.
![image](https://user-images.githubusercontent.com/44631784/57573158-80e8d080-745e-11e9-81aa-feb18b474048.png)
I want to know how I can visualize

**Comment by jingshaoli** [comment]
I make a mistake at the ult 
thanks for you  work,this is a handy tool

**Comment by ankhzaya** [comment]
Hi, I also got just "Visipedia Annotation Toolkit", what is ult? Could you please explain more clearly how to fix it?

**Comment by Sun-Ng** [comment]
> Hi, I also got just "Visipedia Annotation Toolkit", what is ult? Could you please explain more clearly how to fix it?

- Use this address: http://localhost:8008/edit_task/
- annotation tools tutorials：https://github.com/visipedia/annotation_tools/blob/master/tutorials/mice.md
