### ISSUE TITLE
how can i annotate object besides human ? 

### ISSUE THREAD

**Issue by anxu829** [visipedia/annotation_tools#5]
I have successfully  launch your web service but i find that your service can only annotate human and their keypoints , so i was wondering how to config for annotating user-defined objects , like four angles of an 
 milk box ？

**Comment by anxu829** [comment]
i got it , i found the answer in https://github.com/visipedia/annotation_tools/blob/master/tutorials/mice.md

**Comment by Abhijeet241093** [comment]
Even after doing it, person annotation still their, how to remove person annotation ?
