### ISSUE TITLE
local dataset

### ISSUE THREAD

**Issue by r11alaa** [visipedia/annotation_tools#6]
hello @gvanhorn38 ,
I have generated a coco style json file for a local dataset  in my PC
when I use this tool with the original  coco data set everything is ok, but when I'm usign my dataset with my generated json file the images are not loaded to the web browser ( i get empty page with "Visipedia Annotation Toolkit" inside it )
so please can you help with that ?
I'm using 
python 2.7
SimpleHTTPServer
MongoDB shell version v4.0.2

**Comment by kai06046** [comment]
@r11alaa May you kindly give a hint that how you solve the problem? I also need annotations for my local dataset. Thanks!

**Comment by r11alaa** [comment]
Hello,
It was related to the directory in which i must run the python server command. It should be dierctly above the folder that containing your images, and it should be consistent with the url link in the generated json file.
This is as far as i remember :)
Regards

**Comment by leonzgtee** [comment]
@r11alaa， hello， how did you generate the json file in accordance with the image folder@r11alaa， hello， how did you generate the json file in accordance with the image folder

**Comment by leonzgtee** [comment]
@r11alaa， hello， how did you generate the json file in accordance with the image folder
